version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: dordzh99/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/media/
  frontend:
    image: dordzh99/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: dordzh99/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - 9000:80
